### ISSUE TITLE
q

### ISSUE THREAD

**Issue by MikJusen** [VARoGh/Avito_parser#1]
Добрый день Антон, спасибо что поделились скриптом, у меня работает отлично. Подскажите, как часто, минимум, можно его запускать чтобы не забанили ip? Спасибо.

**Comment by VARoGh** [comment]
Привет, @MikJusen. При тестировании скрипта, в цикле запускал его 1 раз в 3-5 минут. Проблем с авито не возникало.

**Comment by MikJusen** [comment]
изредка вылазит это...
ничего кроме урла не менял, просто переименовал в new.py

Traceback (most recent call last):
  File "/home/mix/Telegram-bot_Avito/new.py", line 126, in <module>
    main()
  File "/home/mix/Telegram-bot_Avito/new.py", line 119, in main
    offers = get_offers(data)
  File "/home/mix/Telegram-bot_Avito/new.py", line 90, in get_offers
    for key in data:
TypeError: 'NoneType' object is not iterable
